service: kezbek-promo

frameworkVersion: '3'

plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-3 # Jakarta/Indonesia
  stage: prod
  timeout: 20
  apiGateway:
    restApiId: brvoz49rbj
    restApiRootResourceId: 4f70qpyk4l

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: promo/{proxy+}
          authorizer:
            name: kezbek-promo
            arn: arn:aws:cognito-idp:ap-southeast-1:735185491450:userpool/ap-southeast-1_x635CqCPA
            authorizerId:
              Ref: api-authorizer
      - MQEvent:
          type: MQ
          properties:
            Broker: arn:aws:mq:ap-southeast-1:735185491450:broker:kezbek-backend-mq:b-7f49d384-2141-4097-bda3-198df4b37108
            Queue: promo
            SourceAccessConfigurations:
              - Type: BASIC_AUTH
                URI: arn:aws:secretsmanager:ap-southeast-1:735185491450:secret:MQAccess-9agtwa
