version: '3.8'

## service database postgres, redis, rabbitmq

services:
  database:
    image: postgres:13.2-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
  document_database:
    image: mongo:4.4.4-bionic
    container_name: document_database
    restart: always
    volumes:
      - ./document_database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongo

  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    restart: always
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: redis

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672