version: '3.8'

## service database postgres, redis, rabbitmq

services:

  kezbek-auth:
    container_name: kezbek-auth
    restart: always
    build:
      context: ../app/auth
    ports: 
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    depends_on:
      - database
      - rabbitmq
  
  kezbek-notification:
    container_name: kezbek-notification
    restart: always
    build:
      context: ../app/notification
    ports: 
      - 3004:3004
    environment:
      - NODE_ENV=development
      - PORT=3004
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    depends_on:
      - database
      - rabbitmq

  kezbek-loyalty:
    container_name: kezbek-loyalty
    restart: always
    build:
      context: ../app/loyalty
    ports: 
      - 3001:3001
    environment:
      - NODE_ENV=development
      - PORT=3001
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    depends_on:
      - database
      - rabbitmq
    healthcheck:
      test: curl --fail shttp://localhost:3001/healthcheck || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  kezbek-promo:
    container_name: kezbek-promo
    restart: always
    build:
      context: ../app/promo
    ports: 
      - 3002:3002
    environment:
      - NODE_ENV=development
      - PORT=3002
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    depends_on:
      - database
      - rabbitmq
    healthcheck:
      test: curl --fail shttp://localhost:3002/healthcheck || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  kezbek-transaction:
    container_name: kezbek-transaction
    restart: always
    build:
      context: ../app/transaction
    ports: 
      - 3003:3003
    environment:
      - NODE_ENV=development
      - PORT=3003
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    depends_on:
      - database
      - rabbitmq
    healthcheck:
      test: curl --fail shttp://localhost:3003/healthcheck || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  database:
    image: postgres:13.2-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

networks:
  default:
      name: kezbek-network