## AWS Template KEZBEK RDS DB Instance

Description: 'AWS CloudFormation Template for KEZBEK RDS DB Instance'
Resources:
  kezbek-db-dev:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSecurityGroups:
        - Ref: MyDbSecurityByEC2SecurityGroup
        - Ref: MyDbSecurityByCIDRIPGroup
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: PostgreSQL
      EngineVersion: 12.7
      PubliclyAccessible: true
      MasterUsername: Kezbek-dev
      MasterUserPassword: Kezbek-dev
    DeletionPolicy: Snapshot
## AWS Template Amazon MQ Broker

Description: 'Create a basic Amazon MQ for RabbitMQ broker'
Resources:
  BasicBroker:
    Type: 'AWS::AmazonMQ::Broker'
    Properties:
      AutoMinorVersionUpgrade: 'false'
      BrokerName: MyBasicRabbitBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: RabbitMQ
      EngineVersion: '3.8.6'
      HostInstanceType: mq.t3.micro
      PubliclyAccessible: 'true'
      Users:
        - Password: AmazonMqPassword
          Username: AmazonMqUsername
