service: kezbek-loyalty

frameworkVersion: '3'

plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-3 # Jakarta/Indonesia
  stage: prod
  timeout: 20
  apiGateway:
    restApiId: ${{ secrets.AWS_REST_API_ID }}
    restApiRootResourceId: ${{ secrets.AWS_REST_API_ROOT_RESOURCE_ID }}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: loyalty
