# deployment to serverless

name: Deploy to Serverless Development

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Serverless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - run: cd app/loyalty && npm ci
      - run: cd app/loyalty && npm run test:cov
      - run: cd app/transaction && npm ci
      - run: cd app/transaction && npm run test:cov
      - run: cd app/promo && npm ci
      - run: cd app/promo && npm run test:cov
      # See https://github.com/codecov/example-ci/blob/main/.github/workflows/ci.yml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - run: cd app/loyalty npm run build
      - run: cd app/transaction npm run build
      - run: cd app/promo npm run build

      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage=dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
