service: kezbek-notification

frameworkVersion: '3'

plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-3 # Jakarta/Indonesia
  stage: prod
  timeout: 20
  apiGateway:
    restApiId: brvoz49rbj
    restApiRootResourceId: 4f70qpyk4l

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: notification
          cors: true
          authorizer:
            name: kezbek-notification
            arn: arn:aws:cognito-idp:ap-southeast-1:735185491450:userpool/ap-southeast-1_x635CqCPA
            authorizerId:
              Ref: api-authorizer
